//! Módulo de datos de eventos — schema, validación, firma, almacenamiento local

use anyhow::{Context, Result};
use iroh::SecretKey;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::Path;

/// Schema version
pub const SCHEMA_EVENT: &str = "convoyrun/event/v1";
pub const CTES_VERSION: &str = "1.0";
pub const SCHEMA_CHANNEL: &str = "convoyrun/channel/v1";

/// Public key for entitlement tokens generated by the local admin tool.
pub const CHANNEL_ENTITLEMENT_PUBLIC_KEY: [u8; 32] = [
    0xa1, 0x6a, 0x5b, 0x23, 0xc7, 0x82, 0xb0, 0xae,
    0x9c, 0x7b, 0xe5, 0x8f, 0xf6, 0xbe, 0xe0, 0x1e,
    0x99, 0x78, 0xd5, 0x4f, 0xdc, 0x18, 0x26, 0x62,
    0x5f, 0x7a, 0xd7, 0x9c, 0x8f, 0x66, 0xc8, 0xaf,
];

/// Canales predefinidos del sistema (públicos, sin owner)
pub const SYSTEM_CHANNELS: &[&str] = &[
    "general",
    "ats",
    "ets",
    "convoy",
    "tmp",
];

/// Peer ID especial para canales del sistema
pub const SYSTEM_PEER_ID: &str = "system";

/// Tipos de evento CTES.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum EventType {
    Convoy,
    TruckShow,
    Exploration,
    Competition,
    Meetup,
    Other,
}

fn is_one(value: &u64) -> bool {
    *value == 1
}

fn is_false(value: &bool) -> bool {
    !*value
}

fn parse_rfc3339_epoch_seconds(value: &str) -> Option<i64> {
    chrono::DateTime::parse_from_rfc3339(value)
        .ok()
        .map(|dt| dt.timestamp())
}

fn normalize_loaded_event_document(mut event: EventDocument) -> EventDocument {
    if event.deleted && event.published_at <= 0 {
        event.published_at = parse_rfc3339_epoch_seconds(&event.created_at)
            .unwrap_or_else(|| chrono::Utc::now().timestamp());
    }
    event
}

fn quarantine_corrupt_file(path: &Path, label: &str) {
    if !path.exists() {
        return;
    }
    let stamp = chrono::Utc::now().timestamp();
    let backup_name = format!(
        "{}.corrupt-{}-{}",
        path.file_name().and_then(|name| name.to_str()).unwrap_or(label),
        label,
        stamp
    );
    let backup_path = path.with_file_name(backup_name);
    let _ = std::fs::rename(path, backup_path);
}

fn replace_file(tmp_path: &Path, target_path: &Path) -> Result<()> {
    match std::fs::rename(tmp_path, target_path) {
        Ok(()) => Ok(()),
        Err(err) => {
            if target_path.exists() {
                let _ = std::fs::remove_file(target_path);
                std::fs::rename(tmp_path, target_path)
                    .context("Failed to rename temp file")?;
                Ok(())
            } else {
                Err(err).context("Failed to rename temp file")
            }
        }
    }
}

fn verify_entitlement_token(token: &str) -> Result<ChannelEntitlementPayload> {
    use base64::Engine as _;
    use ed25519_dalek::{Verifier, VerifyingKey};

    let token = token.trim();
    let parts: Vec<&str> = token.split('.').collect();
    if parts.len() != 4 || parts[0] != "crent" || parts[1] != "v1" {
        return Err(anyhow::anyhow!("Invalid entitlement token format"));
    }

    let payload_bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
        .decode(parts[2])
        .context("Invalid entitlement payload encoding")?;
    let signature_bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
        .decode(parts[3])
        .context("Invalid entitlement signature encoding")?;
    if signature_bytes.len() != 64 {
        return Err(anyhow::anyhow!("Invalid entitlement signature length"));
    }

    let payload: ChannelEntitlementPayload = serde_json::from_slice(&payload_bytes)
        .context("Invalid entitlement payload JSON")?;
    if payload.token_type != "patreon_entitlement" {
        return Err(anyhow::anyhow!("Unsupported entitlement type"));
    }

    let verifying_key = VerifyingKey::from_bytes(&CHANNEL_ENTITLEMENT_PUBLIC_KEY)
        .context("Invalid entitlement public key")?;
    let mut signature_array = [0u8; 64];
    signature_array.copy_from_slice(&signature_bytes);
    let signature = ed25519_dalek::Signature::from_bytes(&signature_array);
    verifying_key
        .verify(&payload_bytes, &signature)
        .context("Invalid entitlement signature")?;

    Ok(payload)
}

#[cfg(test)]
mod ctes_fixture_tests {
    use super::{
        canonical_json, EventDocument, ConvoyStore, EventData, EventType, Game, Mode, ProfileRecord,
        Schedule, VoteRecord,
    };
    use base64::Engine as _;
    use ed25519_dalek::{Verifier, VerifyingKey};
    use std::collections::HashMap;

    const VECTORS: &str = include_str!("../tests/fixtures/ctes-v1/vectors.json");
    const DOCUMENTS: [(&str, &str); 5] = [
        ("event", include_str!("../tests/fixtures/ctes-v1/event.json")),
        ("profile", include_str!("../tests/fixtures/ctes-v1/profile.json")),
        ("voteUp", include_str!("../tests/fixtures/ctes-v1/vote-up-r1.json")),
        ("voteDown", include_str!("../tests/fixtures/ctes-v1/vote-down-r2.json")),
        ("tombstone", include_str!("../tests/fixtures/ctes-v1/tombstone-r2.json")),
    ];

    #[test]
    fn verifies_ctes_signed_fixtures() {
        let vectors: serde_json::Value = serde_json::from_str(VECTORS).unwrap();
        let author_id = vectors["testKey"]["authorId"].as_str().unwrap();
        let public_bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
            .decode(author_id.strip_prefix("ed25519:").unwrap())
            .unwrap();
        let public_key: [u8; 32] = public_bytes.try_into().unwrap();
        let verifying_key = VerifyingKey::from_bytes(&public_key).unwrap();

        for (name, source) in DOCUMENTS {
            let mut document: serde_json::Value = serde_json::from_str(source).unwrap();
            let signature_text = document
                .as_object_mut()
                .unwrap()
                .remove("signature")
                .unwrap()
                .as_str()
                .unwrap()
                .to_string();
            let canonical = canonical_json(&document);
            assert_eq!(canonical, vectors["documents"][name]["canonical"]);
            assert_eq!(signature_text, vectors["documents"][name]["signature"]);

            let signature_bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
                .decode(signature_text)
                .unwrap();
            let signature_array: [u8; 64] = signature_bytes.try_into().unwrap();
            let signature = ed25519_dalek::Signature::from_bytes(&signature_array);
            verifying_key.verify(canonical.as_bytes(), &signature).unwrap();
        }
    }

    #[test]
    fn vote_revisions_converge_in_every_delivery_order() {
        let up: VoteRecord = serde_json::from_str(DOCUMENTS[2].1).unwrap();
        let down: VoteRecord = serde_json::from_str(DOCUMENTS[3].1).unwrap();

        for order in [[up.clone(), down.clone()], [down.clone(), up.clone()]] {
            let mut store = ConvoyStore::default();
            for vote in order {
                store.upsert_vote(vote);
            }
            assert_eq!(store.compute_vote_counts(&up.event_id), (0, 1));
            assert_eq!(store.votes[&up.event_id][&up.author_id].revision, 2);
        }
    }

    #[test]
    fn verifies_typed_otes_profile_fixture() {
        let profile: ProfileRecord = serde_json::from_str(DOCUMENTS[1].1).unwrap();
        assert!(profile.validate());
        assert!(profile.verify().unwrap());
        assert_eq!(profile.data.nickname, "Ruta Ñ");
    }

    #[test]
    fn profile_revisions_converge_in_every_delivery_order() {
        let older: ProfileRecord = serde_json::from_str(DOCUMENTS[1].1).unwrap();
        let mut newer = older.clone();
        newer.revision = 2;
        newer.updated_at = "2026-09-04T15:10:00Z".to_string();
        newer.data.nickname = "Ruta Ñ 2".to_string();
        newer.signature = "zzzzzz".to_string();

        for order in [[older.clone(), newer.clone()], [newer.clone(), older.clone()]] {
            let mut store = ConvoyStore::default();
            for profile in order {
                store.upsert_profile(profile);
            }
            let stored = store.profiles.get(&older.author_id).unwrap();
            assert_eq!(stored.revision, 2);
            assert_eq!(stored.data.nickname, "Ruta Ñ 2");
        }
    }

    #[test]
    fn convoy_revisions_and_tombstones_converge_in_every_delivery_order() {
        let live = convoy_record(1, false, "aaa");
        let tombstone = convoy_record(2, true, "bbb");
        let resurrected = convoy_record(3, false, "ccc");

        for (order, expected_revision, expected_deleted, expected_signature) in [
            ([live.clone(), tombstone.clone()], 2, true, "bbb"),
            ([tombstone.clone(), live.clone()], 2, true, "bbb"),
            ([tombstone.clone(), resurrected.clone()], 3, false, "ccc"),
            ([resurrected.clone(), tombstone.clone()], 3, false, "ccc"),
        ] {
            let mut store = ConvoyStore::default();
            for convoy in order {
                store.upsert_convoy(convoy);
            }
            let stored = store.convoys.get("convoy-test").unwrap();
            assert_eq!(stored.revision, expected_revision);
            assert_eq!(stored.deleted, expected_deleted);
            assert_eq!(stored.signature, expected_signature);
        }
    }

    #[test]
    fn tombstone_roundtrip_persists_deleted_state_and_delete_signature() {
        let mut tombstone = convoy_record(2, true, "bbb");
        tombstone.delete_signature = "delete-sig".to_string();

        let serialized = serde_json::to_string(&tombstone).unwrap();
        assert!(serialized.contains("\"deleted\":true"));
        assert!(serialized.contains("\"deleteSignature\":\"delete-sig\""));

        let restored: EventDocument = serde_json::from_str(&serialized).unwrap();
        assert!(restored.deleted);
        assert_eq!(restored.delete_signature, "delete-sig");
        assert_eq!(restored.signature, "bbb");
    }

    #[test]
    fn convoy_rejects_author_replacement_for_same_id() {
        let existing = convoy_record(1, false, "aaa");
        let mut replacement = convoy_record(2, true, "bbb");
        replacement.author_id = "ed25519:BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB".to_string();

        let mut store = ConvoyStore::default();
        store.upsert_convoy(existing.clone());
        store.upsert_convoy(replacement);

        let stored = store.convoys.get("convoy-test").unwrap();
        assert_eq!(stored.author_id, existing.author_id);
        assert!(!stored.deleted);
        assert_eq!(stored.revision, 1);
    }

    fn convoy_record(revision: u64, deleted: bool, signature: &str) -> EventDocument {
        let schedule = Schedule {
            meeting_timestamp: 1_700_000_100,
            start_timestamp: Some(1_700_000_100),
            end_timestamp: None,
            iana_time_zone: "UTC".to_string(),
        };
        EventDocument {
            schema: super::SCHEMA_EVENT.to_string(),
            spec_version: super::CTES_VERSION.to_string(),
            kind: "event".to_string(),
            id: "convoy-test".to_string(),
            revision,
            author_id: "ed25519:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA".to_string(),
            created_at: "2026-09-04T15:00:00Z".to_string(),
            updated_at: "2026-09-04T15:00:00Z".to_string(),
            event: EventData {
                title: "Ruta estable".to_string(),
                description: String::new(),
                language: "es".to_string(),
                translations: HashMap::new(),
                event_type: EventType::Convoy,
                custom_event_type: None,
                game: Game::ATS,
                custom_game: None,
                network: super::NetworkData {
                    server: "Simulation 1".to_string(),
                    name: "Simulation 1".to_string(),
                    access: String::new(),
                },
                schedule: schedule.clone(),
                route: Some(super::Route {
                    origins: vec![super::Place {
                        city: "Montevideo".to_string(),
                        location: "Puerto".to_string(),
                        country: "UY".to_string(),
                    }],
                    waypoints: Vec::new(),
                    destination: Some(super::Place {
                        city: "Buenos Aires".to_string(),
                        location: "Terminal".to_string(),
                        country: "AR".to_string(),
                    }),
                    start_city: String::new(),
                    start_location: String::new(),
                    dest_city: String::new(),
                    dest_location: String::new(),
                }),
                requirements: None,
                links: Vec::new(),
                flyer: None,
                extensions: HashMap::new(),
                mode: Mode::Simulation,
                link: String::new(),
                server: String::new(),
            },
            signature: signature.to_string(),
            peer_id: "peer-a".to_string(),
            nickname: "Driver".to_string(),
            published_at: 1_700_000_000,
            channel: String::new(),
            flyer: None,
            delete_signature: String::new(),
            deleted,
        }
    }
}

impl Default for EventType {
    fn default() -> Self { Self::Convoy }
}

/// Juegos soportados.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum Game {
    ATS,
    ETS2,
    Other,
}

impl Default for Game {
    fn default() -> Self { Self::ATS }
}

/// Modos de servidor legados.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum Mode {
    #[serde(rename = "simulation")]
    Simulation,
    #[serde(rename = "realistic")]
    Realistic,
    #[serde(rename = "arcade")]
    Arcade,
    #[serde(rename = "race")]
    Race,
    #[serde(rename = "other")]
    Other,
}

impl Default for Mode {
    fn default() -> Self { Self::Simulation }
}

/// Lugar dentro de una ruta CTES.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Place {
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub city: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub location: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub country: String,
}

/// Red CTES del evento.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct NetworkData {
    pub server: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub name: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub access: String,
}

/// Requisitos del evento.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Requirements {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dlcs: Vec<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub mods: Vec<String>,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub vehicles: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub notes: String,
}

/// Ruta CTES.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Route {
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub origins: Vec<Place>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub waypoints: Vec<Place>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub destination: Option<Place>,

    #[serde(skip)]
    pub start_city: String,
    #[serde(skip)]
    pub start_location: String,
    #[serde(skip)]
    pub dest_city: String,
    #[serde(skip)]
    pub dest_location: String,
}

/// Enlace público CTES.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Link {
    pub rel: String,
    pub url: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub label: String,
}

/// Traducción opcional de título y descripción.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Translation {
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub title: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub description: String,
}

/// Datos opcionales del flyer CTES.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct FlyerData {
    /// URL de la imagen (catbox o externa). Alias "thumb" para compatibilidad con datos viejos.
    #[serde(alias = "thumb")]
    pub url: String,
    /// Tamaño en bytes
    #[serde(default)]
    pub size: u64,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub media_type: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub digest: String,
}

mod rfc3339_unix_seconds {
    use super::*;
    use serde::{Deserializer, Serializer};

    pub fn serialize<S>(value: &i64, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let dt = chrono::DateTime::<chrono::Utc>::from_timestamp(*value, 0)
            .ok_or_else(|| serde::ser::Error::custom("invalid unix timestamp"))?;
        serializer.serialize_str(&dt.to_rfc3339_opts(chrono::SecondsFormat::Secs, true))
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<i64, D::Error>
    where
        D: Deserializer<'de>,
    {
        let text = String::deserialize(deserializer)?;
        let parsed = chrono::DateTime::parse_from_rfc3339(&text)
            .map_err(serde::de::Error::custom)?;
        Ok(parsed.timestamp())
    }
}

mod opt_rfc3339_unix_seconds {
    use super::*;
    use serde::{Deserializer, Serializer};

    pub fn serialize<S>(value: &Option<i64>, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        match value {
            Some(ts) => super::rfc3339_unix_seconds::serialize(ts, serializer),
            None => serializer.serialize_none(),
        }
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<Option<i64>, D::Error>
    where
        D: Deserializer<'de>,
    {
        let opt = Option::<String>::deserialize(deserializer)?;
        match opt {
            Some(text) => {
                let parsed = chrono::DateTime::parse_from_rfc3339(&text)
                    .map_err(serde::de::Error::custom)?;
                Ok(Some(parsed.timestamp()))
            }
            None => Ok(None),
        }
    }
}

/// Horarios del evento.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Schedule {
    /// Timestamp Unix (UTC) de la reunión
    #[serde(rename = "meetingAt", with = "rfc3339_unix_seconds")]
    pub meeting_timestamp: i64,
    #[serde(default, rename = "startAt", skip_serializing_if = "Option::is_none", with = "opt_rfc3339_unix_seconds")]
    pub start_timestamp: Option<i64>,
    #[serde(default, rename = "endAt", skip_serializing_if = "Option::is_none", with = "opt_rfc3339_unix_seconds")]
    pub end_timestamp: Option<i64>,
    /// Zona horaria IANA del creador (ej: "America/Argentina/Buenos_Aires")
    #[serde(rename = "timeZone")]
    pub iana_time_zone: String,
}

/// Datos del evento.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EventData {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(default, rename = "description", skip_serializing_if = "String::is_empty")]
    pub description: String,
    #[serde(default, rename = "language", skip_serializing_if = "String::is_empty")]
    pub language: String,
    #[serde(default, rename = "translations", skip_serializing_if = "HashMap::is_empty")]
    pub translations: HashMap<String, Translation>,
    #[serde(default, rename = "eventType")]
    pub event_type: EventType,
    #[serde(default, rename = "customEventType", skip_serializing_if = "Option::is_none")]
    pub custom_event_type: Option<String>,
    #[serde(default, rename = "game")]
    pub game: Game,
    #[serde(default, rename = "customGame", skip_serializing_if = "Option::is_none")]
    pub custom_game: Option<String>,
    #[serde(default, rename = "network")]
    pub network: NetworkData,
    #[serde(default, rename = "schedule")]
    pub schedule: Schedule,
    #[serde(default, rename = "route", skip_serializing_if = "Option::is_none")]
    pub route: Option<Route>,
    #[serde(default, rename = "requirements", skip_serializing_if = "Option::is_none")]
    pub requirements: Option<Requirements>,
    #[serde(default, rename = "links", skip_serializing_if = "Vec::is_empty")]
    pub links: Vec<Link>,
    #[serde(default, rename = "flyer", skip_serializing_if = "Option::is_none")]
    pub flyer: Option<FlyerData>,
    #[serde(default, rename = "extensions", skip_serializing_if = "HashMap::is_empty")]
    pub extensions: HashMap<String, serde_json::Value>,

    #[serde(default, skip)]
    pub mode: Mode,
    #[serde(default, skip)]
    pub link: String,
    #[serde(default, skip)]
    pub server: String,
}

/// Documento CTES de evento (publicado por un autor).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EventDocument {
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub schema: String,
    #[serde(rename = "specVersion")]
    pub spec_version: String,
    #[serde(rename = "kind")]
    pub kind: String,
    pub id: String,
    #[serde(default, skip_serializing_if = "is_one")]
    pub revision: u64,
    #[serde(rename = "authorId")]
    pub author_id: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "data")]
    pub event: EventData,
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(default, skip)]
    pub peer_id: String,
    #[serde(default, skip)]
    pub nickname: String,
    #[serde(default, skip)]
    pub published_at: i64,
    #[serde(default, skip)]
    pub channel: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub flyer: Option<FlyerData>,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub delete_signature: String,
    #[serde(default, skip_serializing_if = "is_false")]
    pub deleted: bool,
}

/// Registro de voto
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct VoteRecord {
    pub spec_version: String,
    pub kind: String,
    pub event_id: String,
    pub revision: u64,
    pub author_id: String,
    pub created_at: String,
    pub updated_at: String,
    pub data: VoteData,
    pub signature: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VoteData {
    pub value: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProfileRecord {
    pub spec_version: String,
    pub kind: String,
    pub revision: u64,
    pub author_id: String,
    pub created_at: String,
    pub updated_at: String,
    pub data: ProfileData,
    pub signature: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProfileData {
    pub nickname: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub links: Vec<ProfileLink>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProfileLink {
    pub rel: String,
    pub url: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub label: String,
}

/// Registro de canal (propagado por gossip)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannelRecord {
    pub schema: String,
    /// Nombre interno (siempre lowercase, usado como identificador)
    pub name: String,
    /// Nombre para mostrar en la UI (puede tener mayúsculas, emojis, etc.)
    #[serde(default)]
    pub display_name: String,
    pub creator_peer_id: String,
    /// Peer IDs autorizados por el dueño para publicar en este canal.
    #[serde(default)]
    pub authorized_peer_ids: Vec<String>,
    pub created_at: i64,
    /// Firma ed25519 del payload canónico
    #[serde(default)]
    pub signature: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannelEntitlementPayload {
    #[serde(rename = "type")]
    pub token_type: String,
    pub channel_id: String,
    pub display_name: String,
    pub owner_author_id: String,
    pub issued_at: String,
    pub key_id: String,
}

/// Estado local de convoys (caché)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ConvoyStore {
    pub convoys: HashMap<String, EventDocument>,
    pub votes: HashMap<String, HashMap<String, VoteRecord>>, // convoy_id -> voter_peer_id -> vote
    #[serde(default)]
    pub profiles: HashMap<String, ProfileRecord>,
}

impl EventDocument {
    /// Crea un nuevo documento de evento
    pub fn new(
        peer_id: String,
        revision: u64,
        nickname: String,
        event: EventData,
        schedule: Schedule,
        flyer: Option<FlyerData>,
        channel: String,
        id: Option<String>,
    ) -> Self {
        let now = chrono::Utc::now();
        let now_rfc3339 = now.to_rfc3339_opts(chrono::SecondsFormat::Secs, true);
        let author_id = otes_author_id(&peer_id).unwrap_or_else(|_| peer_id.clone());
        let mut event = event;
        if event.language.is_empty() {
            event.language = "es".to_string();
        }
        if event.network.server.is_empty() {
            event.network.server = event.server.clone();
        }
        if event.network.name.is_empty() {
            event.network.name = event.network.server.clone();
        }
        if event.links.is_empty() && !event.link.is_empty() {
            event.links.push(Link {
                rel: "details".to_string(),
                url: event.link.clone(),
                label: String::new(),
            });
        }
        if event.route.is_none() {
            let mut route = Route::default();
            if !event.route.as_ref().is_some_and(|r| !r.origins.is_empty()) && !event.server.is_empty() {
                route.origins.push(Place {
                    city: event.server.clone(),
                    location: String::new(),
                    country: String::new(),
                });
            }
            event.route = Some(route);
        }
        event.schedule = schedule;
        let meeting_timestamp = event.schedule.meeting_timestamp;
        event.schedule.start_timestamp.get_or_insert(meeting_timestamp);

        Self {
            schema: SCHEMA_EVENT.to_string(),
            spec_version: CTES_VERSION.to_string(),
            kind: "event".to_string(),
            id: id.unwrap_or_else(|| uuid::Uuid::now_v7().to_string()),
            revision,
            author_id,
            created_at: now_rfc3339.clone(),
            updated_at: now_rfc3339,
            event,
            signature: String::new(),
            peer_id,
            nickname,
            published_at: chrono::Utc::now().timestamp(),
            channel,
            flyer,
            delete_signature: String::new(),
            deleted: false,
        }
    }

    /// Serialización canónica para firma (claves ordenadas, sin el campo signature)
    pub fn canonical_json(&self) -> Result<String> {
        // Crear copia sin signature
        let mut copy = self.clone();
        copy.signature = String::new();
        copy.delete_signature = String::new();
        copy.deleted = false;
        if copy.event.network.server.is_empty() {
            copy.event.network.server = copy.event.server.clone();
        }
        if copy.event.network.name.is_empty() {
            copy.event.network.name = copy.event.network.server.clone();
        }
        if copy.event.links.is_empty() && !copy.event.link.is_empty() {
            copy.event.links.push(Link {
                rel: "details".to_string(),
                url: copy.event.link.clone(),
                label: String::new(),
            });
        }
        if copy.event.route.is_none() {
            let mut route = Route::default();
            if !copy.event.server.is_empty() {
                route.origins.push(Place {
                    city: copy.event.server.clone(),
                    location: String::new(),
                    country: String::new(),
                });
            }
            copy.event.route = Some(route);
        }
        let meeting_timestamp = copy.event.schedule.meeting_timestamp;
        copy.event.schedule.start_timestamp.get_or_insert(meeting_timestamp);
        if copy.created_at.is_empty() {
            copy.created_at = chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true);
        }
        if copy.updated_at.is_empty() {
            copy.updated_at = copy.created_at.clone();
        }
        if copy.revision == 1 {
            copy.revision = 0;
        }

        // Serializar con claves ordenadas
        let value = serde_json::to_value(&copy)
            .context("Failed to serialize EventDocument for canonical JSON")?;
        let mut value = value;
        if let Some(obj) = value.as_object_mut() {
            if obj.get("revision").and_then(|v| v.as_u64()) == Some(0) {
                obj.remove("revision");
            }
        }
        Ok(canonical_json(&value))
    }

    /// Firma el registro con la clave secreta
    pub fn sign(&mut self, secret_key: &SecretKey) -> Result<()> {
        use ed25519_dalek::{Signer, SigningKey};

        let canonical = self.canonical_json()?;
        let message = canonical.as_bytes();

        // Convertir SecretKey de iroh a SigningKey de ed25519-dalek
        let key_bytes = secret_key.to_bytes();
        let signing_key = SigningKey::from_bytes(&key_bytes);

        let signature = signing_key.sign(message);
        self.signature = base64::Engine::encode(
            &base64::engine::general_purpose::STANDARD,
            signature.to_bytes(),
        );

        Ok(())
    }

    /// Verifica la firma del registro
    pub fn verify(&self) -> Result<bool> {
        use ed25519_dalek::{Verifier, VerifyingKey};

        if self.signature.is_empty() {
            return Ok(false);
        }

        // Decodificar peer_id a public key (soporta hex y base64)
        let signer_id = if self.author_id.is_empty() {
            &self.peer_id
        } else {
            &self.author_id
        };
        let key_array = match decode_peer_id_bytes(signer_id) {
            Ok(k) => k,
            Err(_) => return Ok(false),
        };
        let verifying_key = VerifyingKey::from_bytes(&key_array).context("Invalid public key")?;

        // Decodificar firma
        let sig_bytes = base64::Engine::decode(
            &base64::engine::general_purpose::STANDARD,
            &self.signature,
        )
        .context("Failed to decode signature")?;

        if sig_bytes.len() != 64 {
            return Ok(false);
        }

        let mut sig_array = [0u8; 64];
        sig_array.copy_from_slice(&sig_bytes);
        let signature = ed25519_dalek::Signature::from_bytes(&sig_array);

        // Verificar
        let canonical = self.canonical_json()?;
        let message = canonical.as_bytes();

        Ok(verifying_key.verify(message, &signature).is_ok())
    }

    pub fn wins_over(&self, existing: &Self) -> bool {
        if self.author_id != existing.author_id {
            return false;
        }
        if self.revision != existing.revision {
            return self.revision > existing.revision;
        }
        if self.deleted != existing.deleted {
            return self.deleted;
        }
        self.signature > existing.signature
    }

    /// Verifica si el convoy aún es válido (no expiró)
    pub fn is_retained(&self, now: i64) -> bool {
        const RETENTION_DAYS: i64 = 3;
        self.event.schedule.meeting_timestamp + RETENTION_DAYS * 86400 > now
    }

    /// Verifica si el convoy se puede publicar (dentro del horizonte)
    pub fn is_within_publish_window(&self, now: i64) -> bool {
        const PUBLISH_HORIZON_DAYS: i64 = 90;
        self.event.schedule.meeting_timestamp <= now + PUBLISH_HORIZON_DAYS * 86400
    }
}

impl VoteRecord {
    pub fn new(event_id: String, author_id: String, value: i32, previous: Option<&Self>) -> Self {
        let now = chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true);
        Self {
            spec_version: CTES_VERSION.to_string(),
            kind: "vote".to_string(),
            event_id,
            revision: previous.map_or(1, |vote| vote.revision.saturating_add(1)),
            author_id,
            created_at: previous.map_or_else(|| now.clone(), |vote| vote.created_at.clone()),
            updated_at: now,
            data: VoteData { value },
            signature: String::new(),
        }
    }

    /// Serialización canónica para firma
    pub fn canonical_json(&self) -> Result<String> {
        let mut value = serde_json::to_value(self)
            .context("Failed to serialize VoteRecord for canonical JSON")?;
        value.as_object_mut().context("VoteRecord must be an object")?.remove("signature");
        Ok(canonical_json(&value))
    }

    /// Firma el voto
    pub fn sign(&mut self, secret_key: &SecretKey) -> Result<()> {
        use ed25519_dalek::{Signer, SigningKey};

        let canonical = self.canonical_json()?;
        let message = canonical.as_bytes();

        let key_bytes = secret_key.to_bytes();
        let signing_key = SigningKey::from_bytes(&key_bytes);

        let signature = signing_key.sign(message);
        self.signature = base64::Engine::encode(
            &base64::engine::general_purpose::URL_SAFE_NO_PAD,
            signature.to_bytes(),
        );

        Ok(())
    }

    /// Verifica la firma del voto
    pub fn verify(&self) -> Result<bool> {
        use ed25519_dalek::{Verifier, VerifyingKey};

        if self.signature.is_empty() {
            return Ok(false);
        }

        let key_array = match decode_peer_id_bytes(&self.author_id) {
            Ok(k) => k,
            Err(_) => return Ok(false),
        };
        let verifying_key = VerifyingKey::from_bytes(&key_array).context("Invalid public key")?;

        let sig_bytes = base64::Engine::decode(
            &base64::engine::general_purpose::URL_SAFE_NO_PAD,
            &self.signature,
        )
        .context("Failed to decode signature")?;

        if sig_bytes.len() != 64 {
            return Ok(false);
        }

        let mut sig_array = [0u8; 64];
        sig_array.copy_from_slice(&sig_bytes);
        let signature = ed25519_dalek::Signature::from_bytes(&sig_array);

        let canonical = self.canonical_json()?;
        let message = canonical.as_bytes();

        Ok(verifying_key.verify(message, &signature).is_ok())
    }

    pub fn validate(&self) -> bool {
        let event_id = uuid::Uuid::parse_str(&self.event_id);
        let created = chrono::DateTime::parse_from_rfc3339(&self.created_at);
        let updated = chrono::DateTime::parse_from_rfc3339(&self.updated_at);
        self.spec_version == CTES_VERSION
            && self.kind == "vote"
            && (1..=9_007_199_254_740_991).contains(&self.revision)
            && event_id.is_ok_and(|id| id.get_version_num() == 7)
            && self.author_id.starts_with("ed25519:")
            && self.author_id.len() == 51
            && decode_peer_id_bytes(&self.author_id).is_ok()
            && matches!(self.data.value, -1..=1)
            && self.created_at.ends_with('Z')
            && self.updated_at.ends_with('Z')
            && created.is_ok()
            && updated.is_ok()
            && created.unwrap() <= updated.unwrap()
    }

    pub fn wins_over(&self, existing: &Self) -> bool {
        if self.revision != existing.revision {
            return self.revision > existing.revision;
        }
        self.signature > existing.signature
    }
}

impl ProfileRecord {
    pub fn new(author_id: String, nickname: String, previous: Option<&Self>) -> Self {
        let now = chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true);
        Self {
            spec_version: CTES_VERSION.to_string(),
            kind: "profile".to_string(),
            revision: previous.map_or(1, |profile| profile.revision.saturating_add(1)),
            author_id,
            created_at: previous.map_or_else(|| now.clone(), |profile| profile.created_at.clone()),
            updated_at: now,
            data: ProfileData { nickname, links: Vec::new() },
            signature: String::new(),
        }
    }

    pub fn canonical_json(&self) -> Result<String> {
        let mut value = serde_json::to_value(self).context("Failed to serialize CTES profile")?;
        value.as_object_mut().context("ProfileRecord must be an object")?.remove("signature");
        Ok(canonical_json(&value))
    }

    pub fn sign(&mut self, secret_key: &SecretKey) -> Result<()> {
        use ed25519_dalek::{Signer, SigningKey};
        let signing_key = SigningKey::from_bytes(&secret_key.to_bytes());
        let signature = signing_key.sign(self.canonical_json()?.as_bytes());
        self.signature = base64::Engine::encode(
            &base64::engine::general_purpose::URL_SAFE_NO_PAD,
            signature.to_bytes(),
        );
        Ok(())
    }

    pub fn verify(&self) -> Result<bool> {
        use ed25519_dalek::{Verifier, VerifyingKey};
        if !self.validate() {
            return Ok(false);
        }
        let verifying_key = VerifyingKey::from_bytes(&decode_peer_id_bytes(&self.author_id)?)?;
        let bytes = base64::Engine::decode(
            &base64::engine::general_purpose::URL_SAFE_NO_PAD,
            &self.signature,
        )?;
        let signature: [u8; 64] = bytes.try_into().map_err(|_| anyhow::anyhow!("Invalid signature length"))?;
        Ok(verifying_key.verify(
            self.canonical_json()?.as_bytes(),
            &ed25519_dalek::Signature::from_bytes(&signature),
        ).is_ok())
    }

    pub fn validate(&self) -> bool {
        let created = chrono::DateTime::parse_from_rfc3339(&self.created_at);
        let updated = chrono::DateTime::parse_from_rfc3339(&self.updated_at);
        self.spec_version == CTES_VERSION
            && self.kind == "profile"
            && (1..=9_007_199_254_740_991).contains(&self.revision)
            && self.author_id.len() == 51
            && decode_peer_id_bytes(&self.author_id).is_ok()
            && !self.data.nickname.trim().is_empty()
            && self.data.nickname.chars().count() <= 32
            && self.data.links.len() <= 10
            && self.created_at.ends_with('Z')
            && self.updated_at.ends_with('Z')
            && created.is_ok() && updated.is_ok()
            && created.unwrap() <= updated.unwrap()
    }

    pub fn wins_over(&self, existing: &Self) -> bool {
        self.revision > existing.revision
            || (self.revision == existing.revision && self.signature > existing.signature)
    }
}

impl ChannelRecord {
    /// Verifica si este canal es del sistema (sin owner)
    pub fn is_system(&self) -> bool {
        self.creator_peer_id == SYSTEM_PEER_ID
    }

    /// Verifica si el peer ID dado es el dueño de este canal
    pub fn is_owner(&self, peer_id: &str) -> bool {
        if self.is_system() {
            return false; // Los canales del sistema no tienen dueño
        }
        self.creator_peer_id == peer_id
    }

    /// Verifica si un peer puede publicar por grant
    pub fn is_authorized(&self, peer_id: &str) -> bool {
        self.authorized_peer_ids.iter().any(|authorized| authorized == peer_id)
    }

    /// Agrega un peer autorizado si no existe
    pub fn add_authorized_peer(&mut self, peer_id: String) -> bool {
        if self.authorized_peer_ids.iter().any(|existing| existing == &peer_id) {
            return false;
        }
        self.authorized_peer_ids.push(peer_id);
        true
    }

    /// Quita un peer autorizado si existe
    pub fn remove_authorized_peer(&mut self, peer_id: &str) -> bool {
        let before = self.authorized_peer_ids.len();
        self.authorized_peer_ids.retain(|existing| existing != peer_id);
        before != self.authorized_peer_ids.len()
    }
}

impl ConvoyStore {
    /// Carga el store desde disco
    pub fn load(data_dir: &Path) -> Result<Self> {
        let store_path = data_dir.join("convoy_store.json");
        if store_path.exists() {
            let store_str = std::fs::read_to_string(&store_path)
                .context("Failed to read convoy store")?;
            let store: Self = match serde_json::from_str(&store_str) {
                Ok(store) => store,
                Err(err) => {
                    eprintln!("[P2P] Failed to parse convoy store: {}", err);
                    quarantine_corrupt_file(&store_path, "convoy_store");
                    return Ok(Self::default());
                }
            };
            Ok(Self {
                convoys: store
                    .convoys
                    .into_iter()
                    .map(|(id, event)| (id, normalize_loaded_event_document(event)))
                    .collect(),
                votes: store.votes,
                profiles: store.profiles,
            })
        } else {
            Ok(Self::default())
        }
    }

    /// Guarda el store a disco (write atómico: temp file + rename)
    pub fn save(&self, data_dir: &Path) -> Result<()> {
        let store_path = data_dir.join("convoy_store.json");
        let tmp_path = data_dir.join("convoy_store.json.tmp");
        std::fs::write(&tmp_path, serde_json::to_string(self)?)
            .context("Failed to write convoy store")?;
        replace_file(&tmp_path, &store_path).context("Failed to rename convoy store")?;
        Ok(())
    }

    /// Agrega o actualiza un convoy
    pub fn upsert_convoy(&mut self, convoy: EventDocument) {
        let convoy = normalize_loaded_event_document(convoy);
        if let Some(existing) = self.convoys.get(&convoy.id) {
            if !convoy.wins_over(existing) {
                return;
            }
        }
        self.convoys.insert(convoy.id.clone(), convoy);
    }

    pub fn upsert_vote(&mut self, vote: VoteRecord) -> bool {
        let event_votes = self.votes.entry(vote.event_id.clone()).or_default();
        if event_votes.get(&vote.author_id).is_some_and(|current| !vote.wins_over(current)) {
            return false;
        }
        event_votes.insert(vote.author_id.clone(), vote);
        true
    }

    pub fn upsert_profile(&mut self, profile: ProfileRecord) -> bool {
        if self.profiles.get(&profile.author_id)
            .is_some_and(|current| !profile.wins_over(current)) {
            return false;
        }
        self.profiles.insert(profile.author_id.clone(), profile);
        true
    }

    /// Calcula el score de un convoy
    pub fn compute_score(&self, convoy_id: &str) -> i32 {
        self.votes
            .get(convoy_id)
            .map(|votes| votes.values().map(|v| v.data.value).sum())
            .unwrap_or(0)
    }

    /// Calcula conteo de votos (upvotes, downvotes) de un convoy
    pub fn compute_vote_counts(&self, convoy_id: &str) -> (i32, i32) {
        self.votes
            .get(convoy_id)
            .map(|votes| {
                let up = votes.values().filter(|v| v.data.value == 1).count() as i32;
                let down = votes.values().filter(|v| v.data.value == -1).count() as i32;
                (up, down)
            })
            .unwrap_or((0, 0))
    }

    /// Lista convoys vigentes (no expirados, no borrados)
    pub fn list_convoys(&self, from_date: Option<i64>, to_date: Option<i64>) -> Vec<&EventDocument> {
        let now = chrono::Utc::now().timestamp();
        let mut convoys: Vec<_> = self
            .convoys
            .values()
            .filter(|c| {
                !c.deleted
                    && c.is_retained(now)
                    && from_date.map_or(true, |from| c.event.schedule.meeting_timestamp >= from)
                    && to_date.map_or(true, |to| c.event.schedule.meeting_timestamp <= to)
            })
            .collect();

        // Ordenar por meeting_timestamp
        convoys.sort_by_key(|c| c.event.schedule.meeting_timestamp);
        convoys
    }

    /// Purge convoys expirados
    pub fn purge_expired(&mut self) {
        let now = chrono::Utc::now().timestamp();
        self.convoys.retain(|_, c| {
            if c.deleted {
                // Keep deleted convoys 7 days for tombstone propagation.
                let published_at = if c.published_at > 0 {
                    c.published_at
                } else {
                    parse_rfc3339_epoch_seconds(&c.created_at).unwrap_or(c.event.schedule.meeting_timestamp)
                };
                published_at + 7 * 86400 > now
            } else {
                c.is_retained(now)
            }
        });
        self.votes.retain(|id, _| self.convoys.contains_key(id));
    }
}

/// Estado local de canales
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ChannelStore {
    pub channels: HashMap<String, ChannelRecord>,
}

impl ChannelStore {
    /// Carga el store desde disco
    pub fn load(data_dir: &Path) -> Result<Self> {
        let store_path = data_dir.join("channel_store.json");
        if store_path.exists() {
            let store_str = std::fs::read_to_string(&store_path)
                .context("Failed to read channel store")?;
            let store: Self = match serde_json::from_str(&store_str) {
                Ok(store) => store,
                Err(err) => {
                    eprintln!("[P2P] Failed to parse channel store: {}", err);
                    quarantine_corrupt_file(&store_path, "channel_store");
                    return Ok(Self::default());
                }
            };
            Ok(store)
        } else {
            Ok(Self::default())
        }
    }

    /// Guarda el store a disco (write atómico: temp file + rename)
    pub fn save(&self, data_dir: &Path) -> Result<()> {
        let store_path = data_dir.join("channel_store.json");
        let tmp_path = data_dir.join("channel_store.json.tmp");
        std::fs::write(&tmp_path, serde_json::to_string(self)?)
            .context("Failed to write channel store")?;
        replace_file(&tmp_path, &store_path).context("Failed to rename channel store")?;
        Ok(())
    }

    /// Crea los canales del sistema (si no existen)
    pub fn ensure_system_channels(&mut self) {
        for &name in SYSTEM_CHANNELS {
            if !self.channels.contains_key(name) {
                self.channels.insert(name.to_string(), ChannelRecord {
                    schema: SCHEMA_CHANNEL.to_string(),
                    name: name.to_string(),
                    display_name: name.to_string(),
                    creator_peer_id: SYSTEM_PEER_ID.to_string(),
                    authorized_peer_ids: Vec::new(),
                    created_at: chrono::Utc::now().timestamp(),
                    signature: String::new(),
                });
            }
        }
    }

    /// Activa un canal Patreon con key firmada
    /// Key format: base64(channel_name|peer_id|signature)
    pub fn activate_channel(
        &mut self,
        entitlement_token: &str,
        owner_peer_id: &str,
        display_name_override: Option<String>,
    ) -> Result<String, String> {
        let payload = verify_entitlement_token(entitlement_token).map_err(|e| e.to_string())?;
        if payload.owner_author_id != owner_peer_id {
            return Err("This entitlement is not for the current owner".to_string());
        }

        let normalized = payload.channel_id.trim().to_lowercase();
        if normalized.is_empty() {
            return Err("Channel id cannot be empty".to_string());
        }
        if self.channels.contains_key(&normalized) {
            return Err("Channel already exists".to_string());
        }

        let display = display_name_override
            .as_deref()
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .map(ToOwned::to_owned)
            .unwrap_or_else(|| {
                let trimmed = payload.display_name.trim();
                if trimmed.is_empty() { normalized.clone() } else { trimmed.to_string() }
            });

        self.channels.insert(normalized.clone(), ChannelRecord {
            schema: SCHEMA_CHANNEL.to_string(),
            name: normalized.clone(),
            display_name: display,
            creator_peer_id: owner_peer_id.to_string(),
            authorized_peer_ids: vec![owner_peer_id.to_string()],
            created_at: chrono::Utc::now().timestamp(),
            signature: String::new(),
        });

        Ok(normalized)
    }

    /// Agrega un colaborador autorizado a un canal
    pub fn grant_channel_access(
        &mut self,
        channel_name: &str,
        peer_id: &str,
        grantee_peer_id: String,
    ) -> Result<(), String> {
        let normalized = channel_name.trim().to_lowercase();
        let channel = self.channels.get_mut(&normalized)
            .ok_or("Channel not found".to_string())?;

        if !channel.is_owner(peer_id) {
            return Err("Not the channel owner".to_string());
        }

        channel.add_authorized_peer(grantee_peer_id);
        Ok(())
    }

    /// Revoca el acceso de un colaborador
    pub fn revoke_channel_access(
        &mut self,
        channel_name: &str,
        peer_id: &str,
        grantee_peer_id: &str,
    ) -> Result<(), String> {
        let normalized = channel_name.trim().to_lowercase();
        let channel = self.channels.get_mut(&normalized)
            .ok_or("Channel not found".to_string())?;

        if !channel.is_owner(peer_id) {
            return Err("Not the channel owner".to_string());
        }

        channel.remove_authorized_peer(grantee_peer_id);
        Ok(())
    }

    /// Cambia el nombre visible del canal (solo owner)
    pub fn rename_channel(
        &mut self,
        channel_name: &str,
        peer_id: &str,
        display_name: String,
    ) -> Result<(), String> {
        let normalized = channel_name.trim().to_lowercase();
        let channel = self.channels.get_mut(&normalized)
            .ok_or("Channel not found".to_string())?;
        if !channel.is_owner(peer_id) {
            return Err("Not the channel owner".to_string());
        }
        let trimmed = display_name.trim();
        if trimmed.is_empty() {
            return Err("Display name cannot be empty".to_string());
        }
        channel.display_name = trimmed.to_string();
        Ok(())
    }

    /// Elimina un canal (solo el owner puede, no se pueden eliminar canales del sistema)
    pub fn delete_channel(&mut self, channel_name: &str, peer_id: &str) -> Result<(), String> {
        let normalized = channel_name.trim().to_lowercase();
        let channel = self.channels.get(&normalized)
            .ok_or("Channel not found".to_string())?;

        if channel.is_system() {
            return Err("Cannot delete system channel".to_string());
        }

        if !channel.is_owner(peer_id) {
            return Err("Not the channel owner".to_string());
        }

        self.channels.remove(&normalized);
        Ok(())
    }

    /// Verifica si un peer específico puede publicar en el canal.
    pub fn can_peer_publish(&self, channel_name: &str, peer_id: &str) -> bool {
        let normalized = channel_name.trim().to_lowercase();
        match self.channels.get(&normalized) {
            None => false,
            Some(ch) => {
                if ch.is_system() {
                    return true;
                }
                if ch.is_owner(peer_id) || ch.is_authorized(peer_id) {
                    return true;
                }
                false
            }
        }
    }

    /// Obtiene un canal por nombre
    pub fn get_channel(&self, name: &str) -> Option<&ChannelRecord> {
        let normalized = name.trim().to_lowercase();
        self.channels.get(&normalized)
    }

    /// Elimina canales con created_at mayor a 180 días
    pub fn purge_expired(&mut self) {
        let cutoff = chrono::Utc::now().timestamp() - 180 * 86400;
        self.channels.retain(|_, ch| ch.created_at > cutoff);
    }
}

/// Registro de lista negra pública (propagado por gossip)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BlacklistRecord {
    pub schema: String,
    pub author_peer_id: String,
    pub blocked: Vec<String>,
    pub updated_at: i64,
    /// Firma ed25519 del payload canónico
    #[serde(default)]
    pub signature: String,
}

impl BlacklistRecord {
    /// Serialización canónica para firma (sin el campo signature)
    pub fn canonical_json(&self) -> Result<String> {
        let mut copy = self.clone();
        copy.signature = String::new();
        let value = serde_json::to_value(&copy)
            .context("Failed to serialize BlacklistRecord for canonical JSON")?;
        Ok(canonical_json(&value))
    }

    /// Firma el registro con la clave secreta
    pub fn sign(&mut self, secret_key: &SecretKey) -> Result<()> {
        use ed25519_dalek::{Signer, SigningKey};

        let canonical = self.canonical_json()?;
        let message = canonical.as_bytes();

        let key_bytes = secret_key.to_bytes();
        let signing_key = SigningKey::from_bytes(&key_bytes);
        let signature = signing_key.sign(message);
        self.signature = base64::Engine::encode(
            &base64::engine::general_purpose::STANDARD,
            signature.to_bytes(),
        );

        Ok(())
    }

    /// Verifica la firma del registro
    pub fn verify(&self) -> Result<bool> {
        use ed25519_dalek::{Verifier, VerifyingKey};

        if self.signature.is_empty() {
            return Ok(false);
        }

        let key_array = decode_peer_id_bytes(&self.author_peer_id)?;
        let verifying_key = VerifyingKey::from_bytes(&key_array)?;

        let sig_bytes = base64::Engine::decode(
            &base64::engine::general_purpose::STANDARD,
            &self.signature,
        )?;
        if sig_bytes.len() != 64 {
            return Ok(false);
        }

        let mut sig_array = [0u8; 64];
        sig_array.copy_from_slice(&sig_bytes);
        let sig = ed25519_dalek::Signature::from_bytes(&sig_array);

        let canonical = self.canonical_json()?;
        Ok(verifying_key.verify(canonical.as_bytes(), &sig).is_ok())
    }
}

/// Estado local de blacklists públicas recibidas por gossip
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct BlacklistStore {
    pub blacklists: HashMap<String, BlacklistRecord>,
}

impl BlacklistStore {
    pub fn load(data_dir: &Path) -> Result<Self> {
        let store_path = data_dir.join("blacklist_store.json");
        if store_path.exists() {
            let s = std::fs::read_to_string(&store_path)
                .context("Failed to read blacklist store")?;
            let store: Self = match serde_json::from_str(&s) {
                Ok(store) => store,
                Err(err) => {
                    eprintln!("[P2P] Failed to parse blacklist store: {}", err);
                    quarantine_corrupt_file(&store_path, "blacklist_store");
                    return Ok(Self::default());
                }
            };
            Ok(store)
        } else {
            Ok(Self::default())
        }
    }

    pub fn save(&self, data_dir: &Path) -> Result<()> {
        let store_path = data_dir.join("blacklist_store.json");
        let tmp_path = data_dir.join("blacklist_store.json.tmp");
        std::fs::write(&tmp_path, serde_json::to_string(self)?)
            .context("Failed to write blacklist store")?;
        replace_file(&tmp_path, &store_path).context("Failed to rename blacklist store")?;
        Ok(())
    }

    pub fn upsert(&mut self, record: BlacklistRecord) {
        self.blacklists.insert(record.author_peer_id.clone(), record);
    }

    /// Elimina blacklists con updated_at mayor a 90 días
    pub fn purge_expired(&mut self) {
        let cutoff = chrono::Utc::now().timestamp() - 90 * 86400;
        self.blacklists.retain(|_, r| r.updated_at > cutoff);
    }
}

// --- Trustlist pública (espejo de Blacklist) ---

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TrustlistRecord {
    pub schema: String,
    pub author_peer_id: String,
    pub trusted: Vec<String>,
    pub updated_at: i64,
    #[serde(default)]
    pub signature: String,
}

impl TrustlistRecord {
    pub fn canonical_json(&self) -> Result<String> {
        let mut copy = self.clone();
        copy.signature = String::new();
        let value = serde_json::to_value(&copy)
            .context("Failed to serialize TrustlistRecord for canonical JSON")?;
        Ok(canonical_json(&value))
    }

    pub fn sign(&mut self, secret_key: &SecretKey) -> Result<()> {
        use ed25519_dalek::{Signer, SigningKey};
        let canonical = self.canonical_json()?;
        let message = canonical.as_bytes();
        let key_bytes = secret_key.to_bytes();
        let signing_key = SigningKey::from_bytes(&key_bytes);
        let signature = signing_key.sign(message);
        self.signature = base64::Engine::encode(
            &base64::engine::general_purpose::STANDARD,
            signature.to_bytes(),
        );
        Ok(())
    }

    pub fn verify(&self) -> Result<bool> {
        use ed25519_dalek::{Verifier, VerifyingKey};
        if self.signature.is_empty() {
            return Ok(false);
        }
        let key_array = decode_peer_id_bytes(&self.author_peer_id)?;
        let verifying_key = VerifyingKey::from_bytes(&key_array)?;
        let sig_bytes = base64::Engine::decode(
            &base64::engine::general_purpose::STANDARD,
            &self.signature,
        )?;
        if sig_bytes.len() != 64 {
            return Ok(false);
        }
        let mut sig_array = [0u8; 64];
        sig_array.copy_from_slice(&sig_bytes);
        let sig = ed25519_dalek::Signature::from_bytes(&sig_array);
        let canonical = self.canonical_json()?;
        Ok(verifying_key.verify(canonical.as_bytes(), &sig).is_ok())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct TrustlistStore {
    pub trustlists: HashMap<String, TrustlistRecord>,
}

impl TrustlistStore {
    pub fn load(data_dir: &Path) -> Result<Self> {
        let store_path = data_dir.join("trustlist_store.json");
        if store_path.exists() {
            let s = std::fs::read_to_string(&store_path)
                .context("Failed to read trustlist store")?;
            let store: Self = match serde_json::from_str(&s) {
                Ok(store) => store,
                Err(err) => {
                    eprintln!("[P2P] Failed to parse trustlist store: {}", err);
                    quarantine_corrupt_file(&store_path, "trustlist_store");
                    return Ok(Self::default());
                }
            };
            Ok(store)
        } else {
            Ok(Self::default())
        }
    }

    pub fn save(&self, data_dir: &Path) -> Result<()> {
        let store_path = data_dir.join("trustlist_store.json");
        let tmp_path = data_dir.join("trustlist_store.json.tmp");
        std::fs::write(&tmp_path, serde_json::to_string(self)?)
            .context("Failed to write trustlist store")?;
        replace_file(&tmp_path, &store_path).context("Failed to rename trustlist store")?;
        Ok(())
    }

    pub fn upsert(&mut self, record: TrustlistRecord) {
        self.trustlists.insert(record.author_peer_id.clone(), record);
    }

    pub fn purge_expired(&mut self) {
        let cutoff = chrono::Utc::now().timestamp() - 90 * 86400;
        self.trustlists.retain(|_, r| r.updated_at > cutoff);
    }
}

/// Almacén de nicks conocidos (peer_id → nick/alias)
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct KnownNicksStore {
    /// peer_id → nick conocido (del gossip)
    #[serde(default)]
    pub nicks: HashMap<String, String>,
    /// peer_id → alias local (definido por el usuario)
    #[serde(default)]
    pub aliases: HashMap<String, String>,
}

impl KnownNicksStore {
    /// Carga el store desde disco
    pub fn load(data_dir: &Path) -> Self {
        let path = data_dir.join("known_nicks.json");
        std::fs::read_to_string(&path)
            .ok()
            .and_then(|s| serde_json::from_str(&s).ok())
            .unwrap_or_default()
    }

    /// Guarda el store a disco (atómico: temp + rename)
    pub fn save(&self, data_dir: &Path) -> Result<()> {
        let path = data_dir.join("known_nicks.json");
        let tmp_path = data_dir.join("known_nicks.json.tmp");
        if let Ok(json) = serde_json::to_string_pretty(self) {
            std::fs::write(&tmp_path, json)
                .context("Failed to write known nicks temp file")?;
            replace_file(&tmp_path, &path).context("Failed to rename known nicks")?;
        }
        Ok(())
    }

    /// Obtiene el nombre a mostrar para un peer_id (prioridad: alias > nick > peer_id truncado)
    pub fn display_name(&self, peer_id: &str) -> String {
        if let Some(alias) = self.aliases.get(peer_id) {
            return alias.clone();
        }
        if let Some(nick) = self.nicks.get(peer_id) {
            return nick.clone();
        }
        // Peer ID truncado como fallback
        if peer_id.len() > 12 {
            format!("{}…{}", &peer_id[..6], &peer_id[peer_id.len()-4..])
        } else {
            peer_id.to_string()
        }
    }

    /// Actualiza el nick conocido de un peer_id (desde gossip)
    pub fn update_nick(&mut self, peer_id: String, nick: String) {
        if !nick.trim().is_empty() && nick.len() <= 64 {
            self.nicks.insert(peer_id, nick);
        }
    }

    /// Define un alias local para un peer_id
    pub fn set_alias(&mut self, peer_id: String, alias: String) {
        if alias.trim().is_empty() {
            self.aliases.remove(&peer_id);
        } else {
            self.aliases.insert(peer_id, alias);
        }
    }
}

/// Decodifica un peer_id (hex o base64) a 32 bytes.
/// iroh usa formato hex (64 chars), pero algunos formatos usan base64.
pub fn decode_peer_id_bytes(peer_id: &str) -> Result<[u8; 32]> {
    fn decode_base64_peer_id(peer_id: &str) -> Result<Vec<u8>> {
        base64::Engine::decode(&base64::engine::general_purpose::URL_SAFE_NO_PAD, peer_id)
            .or_else(|_| base64::Engine::decode(&base64::engine::general_purpose::STANDARD, peer_id))
            .context("Failed to decode base64 peer_id")
    }

    if let Some(encoded) = peer_id.strip_prefix("ed25519:") {
        let bytes = decode_base64_peer_id(encoded).context("Failed to decode CTES author_id")?;
        return bytes.try_into().map_err(|_| anyhow::anyhow!("Invalid CTES author_id length"));
    }
    // Hex format: 64 hex chars = 32 bytes (iroh default)
    if peer_id.len() == 64 && peer_id.chars().all(|c| c.is_ascii_hexdigit()) {
        let bytes = hex::decode(peer_id).context("Failed to decode hex peer_id")?;
        if bytes.len() != 32 {
            anyhow::bail!("Invalid peer_id length: expected 32, got {}", bytes.len());
        }
        let mut key_array = [0u8; 32];
        key_array.copy_from_slice(&bytes);
        return Ok(key_array);
    }
    // Base64 format: fallback
    let bytes = decode_base64_peer_id(peer_id)?;
    if bytes.len() != 32 {
        anyhow::bail!("Invalid peer_id length: expected 32, got {}", bytes.len());
    }
    let mut key_array = [0u8; 32];
    key_array.copy_from_slice(&bytes);
    Ok(key_array)
}

pub fn otes_author_id(peer_id: &str) -> Result<String> {
    let bytes = decode_peer_id_bytes(peer_id)?;
    Ok(format!(
        "ed25519:{}",
        base64::Engine::encode(&base64::engine::general_purpose::URL_SAFE_NO_PAD, bytes)
    ))
}

/// Serialización canónica JSON (claves ordenadas recursivamente)
fn canonical_json(value: &serde_json::Value) -> String {
    match value {
        serde_json::Value::Null => "null".to_string(),
        serde_json::Value::Bool(b) => b.to_string(),
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::String(s) => serde_json::to_string(s).unwrap_or_else(|_| "\"\"".to_string()),
        serde_json::Value::Array(arr) => {
            let items: Vec<String> = arr.iter().map(canonical_json).collect();
            format!("[{}]", items.join(","))
        }
        serde_json::Value::Object(obj) => {
            let mut keys: Vec<_> = obj.keys().collect();
            keys.sort();
            let items: Vec<String> = keys
                .iter()
                .map(|k| format!("{}:{}", serde_json::to_string(k).unwrap_or_else(|_| "\"\"".to_string()), canonical_json(&obj[*k])))
                .collect();
            format!("{{{}}}", items.join(","))
        }
    }
}
